version: "3.7"

services:
  book-management-service:
    init: true
    build:
      dockerfile: ./Dockerfile
    image: book-management-service:latest
    working_dir: /app
    container_name: book-management-service
    depends_on:
      - book-management-service-database
    volumes:
      - sqlite_data:/app/main/database
    ports:
      - '8080:8080'
    restart: on-failure

  book-management-service-database:
    image: alpine:latest
    container_name: book-management-service-database
    volumes:
      - sqlite_data:/data/db
    command: sh -c "apk add --no-cache sqlite && mkdir -p /data/db && tail -f /dev/null"
    restart: on-failure

volumes:
  sqlite_data:
    driver: local

networks:
  default:
    name: book-management-service